@startuml

package App{
    package model {
        class User{
            - namespace
            - email
        }
    }
        note bottom: php artisan make:fillament-resource UserResource --generate

    package migration{
        class Create_User{
            - id 
            - name
        }
    }
    note bottom: php artisan make:fillament-resource UserResource --generate

    package fillament-resource{
        class UserResource{
            +test()
        }
        
    }
    note bottom: php artisan make:fillament-resource UserResource --generate
}


@enduml